In [1]:
%load_ext autoreload
%reload_ext autoreload
%autoreload 2

import time
import numpy as np
from collections import deque

from unityagents import UnityEnvironment
from dqn_agent import Agent

In [2]:
env = UnityEnvironment(file_name="Banana_Linux/Banana.x86_64")

I0514 09:03:48.929460 140623059806016 environment.py:105] 
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 1
        Number of External Brains : 1
        Lesson number : 0
        Reset Parameters :
		
Unity brain name: BananaBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 37
        Number of stacked Vector Observation: 1
        Vector Action space type: discrete
        Vector Action space size (per agent): 4
        Vector Action descriptions: , , , 


In [3]:
# get the default brain
brain_name = env.brain_names[0]
brain = env.brains[brain_name]

In [4]:
env_info = env.reset(train_mode=True)[brain_name]

# number of agents in the environment
print('Number of agents:', len(env_info.agents))

# number of actions
action_size = brain.vector_action_space_size
print('Number of actions:', action_size)

# examine the state space 
state = env_info.vector_observations[0]
print('States look like:', state)
state_size = len(state)
print('States have length:', state_size)

Number of agents: 1
Number of actions: 4
States look like: [1.         0.         0.         0.         0.84408134 0.
 0.         1.         0.         0.0748472  0.         1.
 0.         0.         0.25755    1.         0.         0.
 0.         0.74177343 0.         1.         0.         0.
 0.25854847 0.         0.         1.         0.         0.09355672
 0.         1.         0.         0.         0.31969345 0.
 0.        ]
States have length: 37


In [5]:
env_info = env.reset(train_mode=False)[brain_name] # reset the environment
state = env_info.vector_observations[0]            # get the current state
action_size = brain.vector_action_space_size
state_size = len(state)
score = 0 
while True:
    action = np.random.randint(action_size)        # select an action
    env_info = env.step(action)[brain_name]        # send the action to the environment
    next_state = env_info.vector_observations[0]   # get the next state
    reward = env_info.rewards[0]                   # get the reward
    done = env_info.local_done[0]                  # see if episode has finished
    score += reward                                # update the score
    state = next_state
    time.sleep(0.01)
    if done:                                       # exit loop if episode finished
        break
    
print("Score: {}".format(score))

Score: 0.0


In [6]:
env_info = env.reset(train_mode=True)[brain_name]
state = env_info.vector_observations[0]
action_size = brain.vector_action_space_size
state_size = len(state)
agent = Agent(state_size=state_size, action_size=action_size)
episodes = 5000
scores_window = deque(maxlen=100)
scores = []
for e in range(episodes + 1):
    env_info = env.reset(train_mode=True)[brain_name]
    state = env_info.vector_observations[0]
    state = np.reshape(state, [1, state_size])
    score = 0
    
    for t in range(1000):
        action = agent.act(state)
        env_info = env.step(action)[brain_name]
        next_state = env_info.vector_observations[0]
        next_state = np.reshape(next_state, [1, state_size])
        reward = env_info.rewards[0]
        done = env_info.local_done[0]
        agent.step(state, action, reward, next_state, done)
        state = next_state
        score += reward
        if done:
            print("episode: {}/{}, score: {}, after time: {}".format(e, episodes, score, t))
            break
            
        if ((t+1)% 4) == 0:
            if agent.memory.__len__()>=64:
                agent.replay()
    
    if e==0:
        print(agent.qnetwork.summary())
        agent.save_weights(epoch=0)
    
    if agent.epsilon > agent.epsilon_min:
        agent.epsilon *= agent.epsilon_decay
    
    scores.append(score)
    scores_window.append(score)
    if (e)%100 == 0:
        mean_score = np.mean(scores_window)
        print('\rEpisode {}\tAverage Score: {:.2f}'.format(e, mean_score))
        if mean_score >= 10.0:
            agent.save_weights(epoch=e)
            break

    if e%100 == 0:
        agent.save_weights(epoch=e)

episode: 0/5000, score: 1.0, after time: 299
Model: "q-network"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                multiple                  2432      
_________________________________________________________________
dense_1 (Dense)              multiple                  4160      
_________________________________________________________________
dense_2 (Dense)              multiple                  260       
Total params: 6,852
Trainable params: 6,852
Non-trainable params: 0
_________________________________________________________________
None
Episode 0	Average Score: 1.00
episode: 1/5000, score: 0.0, after time: 299
episode: 2/5000, score: -1.0, after time: 299
episode: 3/5000, score: 1.0, after time: 299
episode: 4/5000, score: 0.0, after time: 299
episode: 5/5000, score: 0.0, after time: 299
episode: 6/5000, score: 1.0, after time: 299
episode: 7/5000, score: 0.0, after

episode: 158/5000, score: 1.0, after time: 299
episode: 159/5000, score: -2.0, after time: 299
episode: 160/5000, score: 1.0, after time: 299
episode: 161/5000, score: 0.0, after time: 299
episode: 162/5000, score: 3.0, after time: 299
episode: 163/5000, score: -2.0, after time: 299
episode: 164/5000, score: 1.0, after time: 299
episode: 165/5000, score: 1.0, after time: 299
episode: 166/5000, score: 2.0, after time: 299
episode: 167/5000, score: -1.0, after time: 299
episode: 168/5000, score: 1.0, after time: 299
episode: 169/5000, score: 0.0, after time: 299
episode: 170/5000, score: 1.0, after time: 299
episode: 171/5000, score: -2.0, after time: 299
episode: 172/5000, score: 0.0, after time: 299
episode: 173/5000, score: 0.0, after time: 299
episode: 174/5000, score: 1.0, after time: 299
episode: 175/5000, score: 0.0, after time: 299
episode: 176/5000, score: 0.0, after time: 299
episode: 177/5000, score: -2.0, after time: 299
episode: 178/5000, score: -1.0, after time: 299
episode

episode: 331/5000, score: 6.0, after time: 299
episode: 332/5000, score: 1.0, after time: 299
episode: 333/5000, score: 0.0, after time: 299
episode: 334/5000, score: 0.0, after time: 299
episode: 335/5000, score: 3.0, after time: 299
episode: 336/5000, score: 1.0, after time: 299
episode: 337/5000, score: 5.0, after time: 299
episode: 338/5000, score: 3.0, after time: 299
episode: 339/5000, score: 4.0, after time: 299
episode: 340/5000, score: 6.0, after time: 299
episode: 341/5000, score: 4.0, after time: 299
episode: 342/5000, score: 8.0, after time: 299
episode: 343/5000, score: 3.0, after time: 299
episode: 344/5000, score: 8.0, after time: 299
episode: 345/5000, score: 4.0, after time: 299
episode: 346/5000, score: 5.0, after time: 299
episode: 347/5000, score: 1.0, after time: 299
episode: 348/5000, score: 7.0, after time: 299
episode: 349/5000, score: 4.0, after time: 299
episode: 350/5000, score: 7.0, after time: 299
episode: 351/5000, score: 7.0, after time: 299
episode: 352/

episode: 504/5000, score: 5.0, after time: 299
episode: 505/5000, score: 7.0, after time: 299
episode: 506/5000, score: 12.0, after time: 299
episode: 507/5000, score: 4.0, after time: 299
episode: 508/5000, score: 15.0, after time: 299
episode: 509/5000, score: -2.0, after time: 299
episode: 510/5000, score: 3.0, after time: 299
episode: 511/5000, score: 8.0, after time: 299
episode: 512/5000, score: 12.0, after time: 299
episode: 513/5000, score: 6.0, after time: 299
episode: 514/5000, score: 5.0, after time: 299
episode: 515/5000, score: 8.0, after time: 299
episode: 516/5000, score: 3.0, after time: 299
episode: 517/5000, score: 15.0, after time: 299
episode: 518/5000, score: 2.0, after time: 299
episode: 519/5000, score: 9.0, after time: 299
episode: 520/5000, score: 4.0, after time: 299
episode: 521/5000, score: 11.0, after time: 299
episode: 522/5000, score: 13.0, after time: 299
episode: 523/5000, score: 8.0, after time: 299
episode: 524/5000, score: 8.0, after time: 299
episod

episode: 677/5000, score: 13.0, after time: 299
episode: 678/5000, score: 8.0, after time: 299
episode: 679/5000, score: 15.0, after time: 299
episode: 680/5000, score: 10.0, after time: 299
episode: 681/5000, score: 19.0, after time: 299
episode: 682/5000, score: 11.0, after time: 299
episode: 683/5000, score: 11.0, after time: 299
episode: 684/5000, score: 8.0, after time: 299
episode: 685/5000, score: 12.0, after time: 299
episode: 686/5000, score: 14.0, after time: 299
episode: 687/5000, score: 9.0, after time: 299
episode: 688/5000, score: 14.0, after time: 299
episode: 689/5000, score: 6.0, after time: 299
episode: 690/5000, score: 14.0, after time: 299
episode: 691/5000, score: 7.0, after time: 299
episode: 692/5000, score: 7.0, after time: 299
episode: 693/5000, score: 14.0, after time: 299
episode: 694/5000, score: 8.0, after time: 299
episode: 695/5000, score: 12.0, after time: 299
episode: 696/5000, score: 8.0, after time: 299
episode: 697/5000, score: 15.0, after time: 299


In [8]:
env_info = env.reset(train_mode=False)[brain_name] # reset the environment
state = env_info.vector_observations[0]            # get the current state
action_size = brain.vector_action_space_size
state_size = len(state)
score = 0 
state_size = len(state)
state = np.reshape(state, [1, state_size])
# agent = Agent(state_size=state_size, action_size=action_size)
# agent.qnetwork.predict(state)
# agent.qnetwork.load_weights('weights_800.h5')
# print('loaded weights')
for t in range(400):
    action = agent.qnetwork.predict(state)[0]
    print(action)
    action = np.argmax(action)
    print(action)
    env_info = env.step(action)[brain_name]
    next_state = env_info.vector_observations[0]
    next_state = np.reshape(next_state, [1, state_size])
    reward = env_info.rewards[0]
    done = env_info.local_done[0]
    score += reward
    state = next_state
    time.sleep(0.1)
    if done:
        break
    
print("Score: {}".format(score))

[5.7285175 5.5063634 5.5527506 5.2674723]
0
[5.8715982 5.657926  5.912666  5.375709 ]
2
[5.955194  5.695024  5.848912  5.7616587]
0
[5.2990847 5.122637  5.001515  5.0271726]
0
[5.363038  5.177574  5.0380983 5.1018434]
0
[5.432827  5.236476  5.0768766 5.1776295]
0
[5.526174  5.3227744 5.1722803 5.2130923]
0
[5.6051145 5.379028  5.21739   5.4257765]
0
[5.5715785 5.333829  5.1644697 5.4080544]
0
[5.6041474 5.3575244 5.2720556 5.20497  ]
0
[5.7288446 5.460854  5.3990493 5.596735 ]
0
[5.7679315 5.491585  5.4182734 5.6370044]
0
[5.9381557 5.6709137 5.78617   5.723701 ]
0
[4.7275    4.6387897 4.6909494 4.932858 ]
3
[4.7321053 4.699362  4.7178125 4.801811 ]
3
[5.5314736 5.315369  5.074117  5.0965323]
0
[5.6566687 5.40619   5.218737  5.2206235]
0
[5.5792065 5.3713703 5.265622  5.1913924]
0
[5.6852074 5.4535565 5.215961  5.387441 ]
0
[5.743995  5.4992537 5.2613573 5.439047 ]
0
[5.8832383 5.612687  5.7609525 5.7133927]
0
[5.326709  5.121482  4.989651  5.0096135]
0
[5.336288 5.138247 4.992927 5.00

[5.206565  4.93907   5.0005927 5.155537 ]
0
[5.364118  5.102184  5.2730317 5.307804 ]
0
[5.3907447 5.1263666 5.305512  5.3356004]
0
[5.1958327 4.9822154 5.2286887 4.9776344]
2
[5.2347302 5.054127  5.0883875 5.077265 ]
0
[5.2907534 5.1014204 5.1015863 5.127726 ]
0
[5.296631 5.102908 5.110882 5.068994]
0
[5.331513 5.127443 5.108514 5.132514]
0
[5.2813807 5.0974503 5.0516744 5.042669 ]
0
[5.326398  5.1367464 5.083863  5.071591 ]
0
[5.366176 5.170806 5.111864 5.092702]
0
[5.5014887 5.316764  5.4491014 5.198855 ]
0
[5.379135  5.2312603 5.2272105 5.132044 ]
0
[5.549981  5.3924637 5.3878536 5.302541 ]
0
[5.610086 5.450442 5.583023 5.450293]
0
[5.5750675 5.4266624 5.5656443 5.4057446]
0
[5.6381397 5.40562   5.2595625 5.447723 ]
0
[5.6353965 5.3572736 5.1343293 5.609775 ]
0
[5.684962 5.391342 5.094878 5.8209  ]
3
[5.877604  5.64285   5.7407093 5.856908 ]
0
[4.6186957 4.5523047 4.5858803 4.720232 ]
3
[4.655871  4.5980034 4.6358895 4.7592125]
3
[4.953949  4.8678412 4.8778048 4.981441 ]
3
[4.95069